/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package petcatalog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Item service. Represents a row in the &quot;PETS_ITEM&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>petcatalog.model.impl.ItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>petcatalog.model.impl.ItemImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Item
 * @generated
 */
@ProviderType
public interface ItemModel extends BaseModel<Item> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item model instance should use the {@link Item} interface instead.
	 */

	/**
	 * Returns the primary key of this item.
	 *
	 * @return the primary key of this item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item.
	 *
	 * @param primaryKey the primary key of this item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this item.
	 *
	 * @return the item ID of this item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item.
	 *
	 * @param itemId the item ID of this item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the product ID of this item.
	 *
	 * @return the product ID of this item
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this item.
	 *
	 * @param productId the product ID of this item
	 */
	public void setProductId(String productId);

	/**
	 * Returns the name of this item.
	 *
	 * @return the name of this item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this item.
	 *
	 * @param name the name of this item
	 */
	public void setName(String name);

	/**
	 * Returns the description of this item.
	 *
	 * @return the description of this item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this item.
	 *
	 * @param description the description of this item
	 */
	public void setDescription(String description);

	/**
	 * Returns the image url of this item.
	 *
	 * @return the image url of this item
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this item.
	 *
	 * @param imageUrl the image url of this item
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the image thumb url of this item.
	 *
	 * @return the image thumb url of this item
	 */
	@AutoEscape
	public String getImageThumbUrl();

	/**
	 * Sets the image thumb url of this item.
	 *
	 * @param imageThumbUrl the image thumb url of this item
	 */
	public void setImageThumbUrl(String imageThumbUrl);

	/**
	 * Returns the price of this item.
	 *
	 * @return the price of this item
	 */
	public double getPrice();

	/**
	 * Sets the price of this item.
	 *
	 * @param price the price of this item
	 */
	public void setPrice(double price);

}